#!/bin/sh

#
# Activate swap, depending on option
#
CONFIG=/etc/milkv-duo.conf
source ${CONFIG}

case "$1" in
  start)

        if [ "$ENABLE_SWAP" == "1" ]; then
        swapon /dev/mmcblk0p3
        fi
        ;;
  stop)
        ;;
  restart|reload)
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
