#!/bin/sh
${CVI_SHOPTS}

#
# Start firmware
#
export USERDATAPATH=/mnt/data/
export SYSTEMPATH=/mnt/system/

CONFIG=/etc/milkv-duo.conf
source ${CONFIG}

case "$1" in
  start)
        echo "init mpp system..."
        if [ -d $SYSTEMPATH/ko ]; then
                sh $SYSTEMPATH/ko/loadsystemko.sh
        fi

        echo "Starting app..."

        if [ -f $SYSTEMPATH/duo-init.sh ]; then
                . $SYSTEMPATH/duo-init.sh &
        fi

        if [ -f $SYSTEMPATH/blink.sh ]; then
                . $SYSTEMPATH/blink.sh &
        fi

        if [ "$DUO_USB_FUNC" == "RNDIS" ]; then
                if [ -f $SYSTEMPATH/usb-rndis.sh ]; then
                        . $SYSTEMPATH/usb-rndis.sh &
                fi
        elif [ "$DUO_USB_FUNC" == "HOST" ]; then
                if [ -f $SYSTEMPATH/usb-host.sh ]; then
                        . $SYSTEMPATH/usb-host.sh &
                fi
        elif [ "$DUO_USB_FUNC" == "MASS-STORAGE" ]; then
                if [ -f $SYSTEMPATH/usb-mass-storage.sh ]; then
                        . $SYSTEMPATH/usb-mass-storage.sh &
                fi
        fi

        if [ -f $USERDATAPATH/auto.sh ]; then
                usleep 30000
                . $USERDATAPATH/auto.sh &
		exit 1
        fi
	if [ -f $SYSTEMPATH/auto.sh ]; then
                usleep 30000
                . $SYSTEMPATH/auto.sh &
        fi
        ;;
  stop)
        ;;
  restart|reload)
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
